FROM php:5.6.33-apache-jessie

RUN docker-php-ext-install -j$(nproc) pdo_mysql mysql mysqli

# RUN apt-get update && apt-get install -y mysql-server

RUN a2enmod rewrite
RUN usermod -u 1000 www-data
RUN usermod -G staff www-data